### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jerdog** [gnobal/Dindy#1]
@gnobal this looks really pretty cool and great you're doing this open source. I did have a question about license as I noticed you didn't include one.

**Comment by gnobal** [comment]
Hey @jerdog. Thanks for your interest in Dindy. Didn't think anyone would care about it :) I do want to put it under the Apache license. Was just lazy about it :) If it matters to you, I'll do it sometime this week. Otherwise you're welcome to do what you will with the code.

**Comment by jerdog** [comment]
Thanks. Was just looking things over and thought I would see what the license was in case I decided to do something with it.

**Comment by gnobal** [comment]
Consider this "permission" to do whatever you want with the code :)

(Note that it was written originally for Android 1.5 and it's my first Android project. So... sorry :)

**Comment by jerdog** [comment]
Hah - no worries. Thanks
